### ISSUE TITLE
Suggestions to your init.el

### ISSUE THREAD

**Issue by ReneFroger** [wbolster/dotfiles#2]
After studying your Emacs configuration (Nederlanders zie je hier niet zo vaak trouwens), what about using https://github.com/jwiegley/use-package to group your package configurations, and group them into different files in one directory, and lazyloading them (only load the files when needed) in your autoloader.
For example `config-magit.el` with your magit settings and keybindings in use-package declaration, with the following sentence `(provide 'config-magit)` included:

Then 

```
 (require config-foobar
              config-magit)
```

In your init.el

**Comment by wbolster** [comment]
yeah, you're right, it's a bit of mess. i only recently converted from vim, and my focus was more on getting features working the way i wanted (resulting in a few melpa packages already), not on the cleanliness of my config.

i should take a closer look at `use-package` since it seems quite a nice way to keep things neatly organised.

(en er zijn best wat emacs-gebruikers in .nl hoor :))
